from __future__ import annotations

DEFAULT_STOPAN_CONFIG = "/etc/stopan/stopan.yaml"

DEFAULT_NODE_BIND_ADDR = "[::]:50051"
DEFAULT_NODE_ADVERTISE_ADDR = ""
DEFAULT_NODE_IDENTITY_FILE = "/var/lib/stopan/state/node_id.txt"
DEFAULT_NODE_CATALOG_FILE = "/var/lib/stopan/state/catalog.sqlite"

DEFAULT_STORAGE_LOCAL_CHUNK_DIR = "/var/lib/stopan/data/chunks"
DEFAULT_STORAGE_CUSTODY_DIR = "/var/lib/stopan/custody"

DEFAULT_CLUSTER_TOKEN = ""
DEFAULT_CLUSTER_SEEDS: tuple[str, ...] = ()

DEFAULT_PROTECTION_REMOTE_COPIES = 3
DEFAULT_PROTECTION_STRICT_REMOTE_COPIES = False
DEFAULT_PROTECTION_EC_K = 2
DEFAULT_PROTECTION_EC_M = 1

DEFAULT_BACKUP_WORKERS = 4

DEFAULT_METADATA_PACK_COPIES = 3
DEFAULT_METADATA_STRICT_PACK_COPIES = False
DEFAULT_METADATA_PACK_DISCOVERY_MAX_CANDIDATES = 10
DEFAULT_METADATA_PACK_TARGET_PARALLELISM = 4
DEFAULT_METADATA_PACK_RPC_TIMEOUT_S = 60.0
DEFAULT_METADATA_CLI_WARNING_LIMIT = 10

DEFAULT_GRPC_MAX_MESSAGE_BYTES = 8 * 1024 * 1024
DEFAULT_GRPC_KEEPALIVE_TIME_MS = 120_000
DEFAULT_GRPC_KEEPALIVE_TIMEOUT_MS = 20_000
DEFAULT_GRPC_KEEPALIVE_PERMIT_WITHOUT_CALLS = False

DEFAULT_STORAGE_RPC_WORKERS = 64
DEFAULT_STORAGE_COMMIT_WORKERS = 16
DEFAULT_STORAGE_COMMIT_QUEUE_ITEMS = 256
DEFAULT_STORAGE_MAX_CHUNK_SIZE = 8 * 1024 * 1024

DEFAULT_REPLICATION_TARGET_PARALLELISM = 4
DEFAULT_REPLICATION_PROBE_BATCH_HASHES = 2048
DEFAULT_REPLICATION_STREAM_INFLIGHT = 64
DEFAULT_REPLICATION_PROBE_TIMEOUT_S = 10.0
DEFAULT_REPLICATION_STREAM_TIMEOUT_S = 60.0
DEFAULT_REPLICATION_COMMIT_EVERY = 100

DEFAULT_VERIFY_TARGET_PARALLELISM = 4
DEFAULT_VERIFY_PROBE_BATCH_HASHES = 2048
DEFAULT_VERIFY_PROBE_TIMEOUT_S = 10.0

DEFAULT_RESTORE_BATCH_TARGET_PARALLELISM = 4
DEFAULT_RESTORE_PREFETCH_WINDOW = 32
DEFAULT_RESTORE_RPC_TIMEOUT_S = 5.0

DEFAULT_MEMBERSHIP_PROTOCOL_PERIOD_S = 1.0
DEFAULT_MEMBERSHIP_BOOTSTRAP_RETRY_INTERVAL_S = 5.0
MEMBERSHIP_BOOTSTRAP_RETRY_MAX_INTERVAL_S = 30.0
DEFAULT_MEMBERSHIP_PING_TIMEOUT_S = 0.25
DEFAULT_MEMBERSHIP_RPC_TIMEOUT_S = 2.0
DEFAULT_MEMBERSHIP_SUSPECT_TIMEOUT_S = 6.0
DEFAULT_MEMBERSHIP_INDIRECT_PING_FANOUT = 3
DEFAULT_MEMBERSHIP_MAX_GOSSIP_EVENTS = 20
DEFAULT_MEMBERSHIP_GOSSIP_TTL_S = 60.0

DEFAULT_METADATA_PASSPHRASE_FILE = "/etc/stopan/metadata.passphrase"
DEFAULT_METADATA_OWNER_ID = ""
DEFAULT_METADATA_IDENTITY_FILE = "/etc/stopan/metadata_identity.json"
DEFAULT_METADATA_OBJECT_GRAPH_AUTO_EXPORT = False
DEFAULT_METADATA_OBJECT_STORE_DIR = "/var/lib/stopan/metadata/object_store"
DEFAULT_METADATA_OBJECT_GRAPH_INCLUDE_PROTECTION = True
DEFAULT_METADATA_OBJECT_GRAPH_AUTO_PACK = False
DEFAULT_METADATA_GENERATED_PACK_DIR = "/var/lib/stopan/metadata/packs/generated"
DEFAULT_METADATA_RECOVERED_PACK_DIR = "/var/lib/stopan/metadata/packs/recovered"
DEFAULT_METADATA_CUSTODY_PACK_STORE_DIR = "/var/lib/stopan/custody/metadata_packs"
DEFAULT_METADATA_MAX_DISTRIBUTED_PACK_BYTES = 64 * 1024 * 1024
DEFAULT_METADATA_MAX_DISTRIBUTED_PACKS_PER_OWNER = 8
DEFAULT_METADATA_MAX_DISTRIBUTED_PACK_BYTES_PER_OWNER = 512 * 1024 * 1024
DEFAULT_METADATA_MAX_DISTRIBUTED_PACK_STORE_BYTES = 10 * 1024 * 1024 * 1024
DEFAULT_METADATA_SCRYPT_N = 32_768
DEFAULT_METADATA_SCRYPT_R = 8
DEFAULT_METADATA_SCRYPT_P = 1
DEFAULT_METADATA_KEY_LENGTH = 32

DEFAULT_GC_GENERATED_CHUNK_GRACE_HOURS = 48.0
DEFAULT_GC_RECEIVED_CHUNK_MAX_AGE_DAYS = 0
DEFAULT_GC_RECEIVED_EC_MAX_AGE_DAYS = 0
DEFAULT_GC_GENERATED_METADATA_GRAPH_GRACE_HOURS = 48.0
DEFAULT_GC_GENERATED_METADATA_PACK_GRACE_HOURS = 48.0
DEFAULT_GC_RECEIVED_METADATA_PACK_MAX_AGE_DAYS = 0
DEFAULT_GC_RECOVERED_METADATA_PACK_MAX_AGE_DAYS = 0

DEFAULT_EC_PACK_SIZE_BYTES = 8 * 1024 * 1024
