from __future__ import annotations


EXAMPLE_CONFIG = """# Stopan node configuration
#
# This file is suitable both for a real machine and for Docker.
# CLI arguments may override these values for one-off commands.

node:
  bind_addr: "0.0.0.0:50051"
  advertise_addr: "192.168.1.42:50051"
  repo_store_dir: "/var/lib/stopan/node_store"
  local_shard_dir: "/var/lib/stopan/local_cas"
  db_file: "/var/lib/stopan/backup_index.db"

cluster:
  token: "oficina-demo"
  seeds:
    - "192.168.1.42:50051"
    - "192.168.1.43:50051"
    - "192.168.1.44:50051"

protection:
  remote_copies: 3
  strict_remote_copies: true

grpc:
  max_message_bytes: 8388608

storage:
  rpc_workers: 64
  commit_workers: 16
  commit_queue_items: 256
  max_chunk_size: 1048576

replication:
  target_parallelism: 4
  probe_batch_hashes: 2048
  stream_inflight: 64
  probe_timeout_s: 10.0
  stream_timeout_s: 60.0
  commit_every: 100

verify:
  target_parallelism: 4
  probe_batch_hashes: 2048
  probe_timeout_s: 10.0

restore:
  batch_target_parallelism: 4
  prefetch_window: 32
  rpc_timeout_s: 5.0

membership:
  protocol_period_s: 1.0
  ping_timeout_s: 0.25
  rpc_timeout_s: 2.0
  suspect_timeout_s: 6.0
  indirect_ping_fanout: 3
  max_gossip_events: 20
  gossip_ttl_s: 60.0
metadata:
  # Secret used to encrypt/decrypt the local metadata vault and packs.
  passphrase_file: "/etc/stopan/metadata.passphrase"

  # Public identity used to discover distributed metadata packs.
  # If owner_id is empty, Stopan can read it from identity_file.
  owner_id: ""
  identity_file: "/etc/stopan/metadata_identity.json"

  # Incremental, deduplicated encrypted metadata vault.
  object_graph_auto_export: false
  object_store_dir: "/var/lib/stopan/metadata_object_store"
  object_graph_include_protection: true
  object_graph_auto_pack: false
  object_pack_dir: ""

  # Local storage for encrypted metadata packs received from / prepared for P2P.
  distributed_pack_store_dir: "/var/lib/stopan/metadata_distributed_packs"
  pack_copies: 3
  strict_pack_copies: false
  max_distributed_pack_bytes: 67108864
  max_distributed_packs_per_owner: 8
  max_distributed_pack_bytes_per_owner: 536870912
  max_distributed_pack_store_bytes: 10737418240
  # 0 disables age-based pruning. Set e.g. 90 for periodic maintenance.
  scrypt_n: 32768
  scrypt_r: 8
  scrypt_p: 1
  key_length: 32
gc:
  # Local user CAS: chunks no longer referenced by local metadata are kept
  # for this grace period before deletion.
  local_cas_grace_hours: 48.0

  # Restore output directories generated by Stopan.
  # 0 disables age-based cleanup.
  restore_output_max_age_days: 0

  # Node storage CAS: age-based administrative pruning.
  # 0 disables pruning. Use carefully: deleting chunks may degrade remote protection.
  node_cas_max_age_days: 0

  # Encrypted metadata object store mark & sweep grace period.
  metadata_object_store_grace_hours: 48.0

  # Local .stopanmetapack files generated from the object store.
  metadata_object_pack_grace_hours: 48.0

  # Distributed metadata pack store retention.
  # 0 disables age-based pruning.
  distributed_pack_max_age_days: 0
"""
