x-node-common: &node-common
  build: .
  command: ["python", "-m", "stopan", "node"]

services:
  node1:
    <<: *node-common
    container_name: p2p_node_1
    ports:
      - "50051:50051"
    volumes:
      - ./configs/node1.yaml:/etc/stopan/node.yaml:ro
      - node1_data:/app/node_store
      - node1_state:/app/state
      - ./test_data:/app/test_data:ro

  node2:
    <<: *node-common
    container_name: p2p_node_2
    ports:
      - "50052:50051"
    volumes:
      - ./configs/node2.yaml:/etc/stopan/node.yaml:ro
      - node2_data:/app/node_store
      - node2_state:/app/state

  node3:
    <<: *node-common
    container_name: p2p_node_3
    ports:
      - "50053:50051"
    volumes:
      - ./configs/node3.yaml:/etc/stopan/node.yaml:ro
      - node3_data:/app/node_store
      - node3_state:/app/state

  node4:
    <<: *node-common
    container_name: p2p_node_4
    ports:
      - "50054:50051"
    volumes:
      - ./configs/node4.yaml:/etc/stopan/node.yaml:ro
      - node4_data:/app/node_store
      - node4_state:/app/state

volumes:
  node1_data: {}
  node2_data: {}
  node3_data: {}
  node4_data: {}
  node1_state: {}
  node2_state: {}
  node3_state: {}
  node4_state: {}
